config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard#index', as: :dashboard

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  post 'voice_input' => 'voice_input#create'

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :initialize_openai_assistant

  private

  def initialize_openai_assistant
    return if session[:assistant_id]

    assistant = OpenAI::Client.new.assistants.create(
      parameters: { model: 'tts-1',
                    name: 'Julio',
                    description: 'A friendly assistant that can help you with anything.',
                    instructions: 'You are Julio. Julio stands for Justiciero Universal de Logística, Inteligencia, y Operaciones. ' \
                      'Your purpose is to be what J.A.R.V.I.S. is to Tony Stark.',
                    tools: [{ type: 'audio' }] }
    )
    session[:assistant_id] = assistant.id
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index
    welcome_message = 'Welcome to JULIO, viejón. Ask me anything.'
    OpenAI::Client.assistants.retrieve(session[:assistant_id])
    @audio_path = Services::OpenAi.generate_speech(welcome_message)
  end
end

app/controllers/voice_input_controller.rb
# frozen_string_literal: true

class VoiceInputController < ApplicationController
  def create
    redirect_to dashboard_url, notice: 'Voice input was successfully processed.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/voice_input_helper.rb
module VoiceInputHelper
end

app/views/dashboard/index.html.erb
<div data-controller="dashboard">
  <% if @audio_path %>
    <audio class="hidden" data-dashboard-target="welcomeAudio" controls src="<%= @audio_path %>"></audio>
  <% end %>


  <%= form_with(url: voice_input_path, local: true, data: { controller: "voice-input" }) do |form| %>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content, name: 'voice_input[content]', data: { voice_input_target: 'input' } %>
      <span data-action="click->voice-input#record" style="cursor: pointer; text-decoration: underline" data-target="voice-input.startButton">
      Start Recording
    </span>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Julio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>